networks:
  local:
  traefik:
    external: true
services:
  pwa:
    image: node:latest
    working_dir: /work
    command: "yarn preview --host 0.0.0.0 --port 5000"
    volumes:
      - ./:/work
      - ./.yarnrc:/.yarnrc
      - ./.yarn:/.yarn
    user: "${UID}:${GID}"
    networks:
      local: {}
      traefik: {}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=false"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}pwa"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}pwa.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}middle.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}middle"

  anonymous_authenticator:
    image: node:latest
    working_dir: /work
    command: "yarn serve-anonymous-authenticator --host 0.0.0.0 --port 5001"
    volumes:
      - ./:/work
      - ./.yarnrc:/.yarnrc
      - ./.yarn:/.yarn
    user: "${UID}:${GID}"
    networks:
      local: {}
      traefik: {}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=false"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}anonymous_authenticator"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}anonymous_authenticator.loadbalancer.server.port=5001"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}middle.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}middle"

version: '3.7'
